name: 'ngrok-macos'

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose tmate or ngrok mode'
        required: false
        default: 'ngrok'

jobs:
  ssh-debug:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 检出你的代码仓库

      - name: Choose mode ngrok (macos)
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }} 
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          MODE=${{ github.event.inputs.mode }}
          bash ./${MODE}2actions.sh  # 使用相对路径执行脚本
        shell: bash
        
      - name: Sleep
        run: sleep 6h
